<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SystemEventSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $data = [
            [
                'id'                => 1,
                'system_event_main' => 'evt_def_closed_system_001',
                'parent_id'         => null,
                'event_key'         => 'system_default_closed',
                'event_name'        => 'Pendaftaran Default Sistem (Closed)',
                'category'          => 'recruitment_period',
                'is_active'         => 1,
                'is_default'        => 1,
                'status_override'   => 'closed',
                'start_at'          => null,
                'end_at'            => null,
                'description'       => 'Sistem penutupan default jika tidak ada periode pendaftaran aktif.',
                'action_url'        => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 2,
                'system_event_main' => 'evt_rec_odd_template_002',
                'parent_id'         => null,
                'event_key'         => 'recruitment_odd_semester',
                'event_name'        => 'Open Recruitment Asisten - Semester Ganjil',
                'category'          => 'recruitment_period',
                'is_active'         => 0,
                'is_default'        => 0,
                'status_override'   => 'auto',
                'start_at'          => '2026-09-01 00:00:00',
                'end_at'            => '2026-09-30 23:59:59',
                'description'       => 'Periode pendaftaran calon asisten untuk semester ganjil.',
                'action_url'        => '/student/registration',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 3,
                'system_event_main' => 'evt_rec_even_template_003',
                'parent_id'         => null,
                'event_key'         => 'recruitment_even_semester',
                'event_name'        => 'Open Recruitment Asisten - Semester Genap',
                'category'          => 'recruitment_period',
                'is_active'         => 0,
                'is_default'        => 0,
                'status_override'   => 'auto',
                'start_at'          => '2027-02-01 00:00:00',
                'end_at'            => '2027-02-28 23:59:59',
                'description'       => 'Periode pendaftaran calon asisten untuk semester genap.',
                'action_url'        => '/student/registration',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 4,
                'system_event_main' => 'evt_coming_soon_004',
                'parent_id'         => null,
                'event_key'         => 'announcement_coming_soon',
                'event_name'        => 'Seleksi Wawancara Tahap 2',
                'category'          => 'recruitment_stage',
                'is_active'         => 1,
                'is_default'        => 0,
                'status_override'   => 'coming_soon',
                'start_at'          => '2026-10-15 08:00:00',
                'end_at'            => '2026-10-20 17:00:00',
                'description'       => 'Tahapan wawancara akan segera dibuka dalam beberapa hari lagi.',
                'action_url'        => '/student/interview-schedule',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 5,
                'system_event_main' => 'evt_closing_soon_005',
                'parent_id'         => 2,
                'event_key'         => 'recruitment_closing_soon',
                'event_name'        => 'Pengumpulan Berkas Pendaftaran (Mendekati Deadline)',
                'category'          => 'recruitment_stage',
                'is_active'         => 1,
                'is_default'        => 0,
                'status_override'   => 'open',
                'start_at'          => '2026-09-25 00:00:00',
                'end_at'            => '2026-10-05 23:59:59',
                'description'       => 'Pendaftaran akan segera ditutup dalam waktu dekat! Segera selesaikan unggah berkas.',
                'action_url'        => '/student/verification',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 6,
                'system_event_main' => 'evt_voting_system_006',
                'parent_id'         => null,
                'event_key'         => 'system_voting_chief',
                'event_name'        => 'Pemilihan Ketum / Koordinator Asisten',
                'category'          => 'general_announcement',
                'is_active'         => 1,
                'is_default'        => 0,
                'status_override'   => 'open',
                'start_at'          => '2026-10-01 08:00:00',
                'end_at'            => '2026-10-10 20:00:00',
                'description'       => 'Buka tautan berikut untuk memberikan suara Anda.',
                'action_url'        => '/vote/chief-selection',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 7,
                'system_event_main' => 'evt_presensi_rapat_007',
                'parent_id'         => null,
                'event_key'         => 'attendance_meeting',
                'event_name'        => 'Presensi Rapat Rutin Asisten',
                'category'          => 'general_announcement',
                'is_active'         => 1,
                'is_default'        => 0,
                'status_override'   => 'open',
                'start_at'          => '2026-10-02 13:00:00',
                'end_at'            => '2026-10-02 18:00:00',
                'description'       => 'Presensi kehadiran rapat koordinasi asisten.',
                'action_url'        => '/attendance/meeting',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 8,
                'system_event_main' => 'evt_presensi_divisi_008',
                'parent_id'         => null,
                'event_key'         => 'attendance_division_class',
                'event_name'        => 'Presensi Internal Training Divisi',
                'category'          => 'general_announcement',
                'is_active'         => 1,
                'is_default'        => 0,
                'status_override'   => 'open',
                'start_at'          => '2026-10-02 09:00:00',
                'end_at'            => '2026-10-02 12:00:00',
                'description'       => 'Presensi pelatihan pembelajaran divisi.',
                'action_url'        => '/attendance/division-class',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 9,
                'system_event_main' => 'evt_order_pdh_009',
                'parent_id'         => null,
                'event_key'         => 'order_pdh_uniform',
                'event_name'        => 'Pemesanan Seragam PDH Asisten Baru',
                'category'          => 'general_announcement',
                'is_active'         => 1,
                'is_default'        => 0,
                'status_override'   => 'open',
                'start_at'          => '2026-10-01 00:00:00',
                'end_at'            => '2026-10-15 23:59:59',
                'description'       => 'Pengisian ukuran dan pemesanan pakaian dinas harian (PDH).',
                'action_url'        => '/order/pdh-uniform',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 10,
                'system_event_main' => 'evt_presensi_umum_010',
                'parent_id'         => null,
                'event_key'         => 'attendance_general',
                'event_name'        => 'Presensi Acara Kebersamaan / Gathering',
                'category'          => 'general_announcement',
                'is_active'         => 1,
                'is_default'        => 0,
                'status_override'   => 'open',
                'start_at'          => '2026-10-02 07:00:00',
                'end_at'            => '2026-10-02 17:00:00',
                'description'       => 'Presensi umum kehadiran kegiatan outdoor/gathering.',
                'action_url'        => '/attendance/general',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'id'                => 11,
                'system_event_main' => 'evt_bukti_piket_011',
                'parent_id'         => null,
                'event_key'         => 'submission_duty_piket',
                'event_name'        => 'Upload Bukti Kehadiran / Foto Piket Lab',
                'category'          => 'general_announcement',
                'is_active'         => 1,
                'is_default'        => 0,
                'status_override'   => 'open',
                'start_at'          => '2026-10-01 00:00:00',
                'end_at'            => '2026-12-31 23:59:59',
                'description'       => 'Form unggah bukti pelaksanaan piket laboratorium harian.',
                'action_url'        => '/duty/upload-proof',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
        ];

        $this->db->table('system_event_settings')->insertBatch($data);
    }
}
