<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UsersSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'student_number'    => '22.11.4501',
                'full_name'         => 'Igo Tegar Prambudhy',
                'email'             => 'igo.tegar@students.amikom.ac.id',
                'email_verified_at' => date('Y-m-d H:i:s'),
                'phone_number'      => '081234567890',
                'password'          => password_hash('password123', PASSWORD_BCRYPT),
                'faculty_id'        => 1,
                'study_program_id'  => 1,
                'class_id'          => 1,
                'place_of_birth'    => 'Banyumas',
                'date_of_birth'     => '2003-05-12',
                'gender'            => 'male',
                'province'          => 'Jawa Tengah',
                'regency'           => 'Banyumas',
                'subdistrict'       => 'Purwokerto Selatan',
                'village'           => 'Karangklesem',
                'address'           => 'Jl. Pahlawan No. 45',
                'gpa'               => 3.85,
                'profile'           => 'default.jpg',
                'is_verified'        => 1,
                'status_account'    => 'active',
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'student_number'    => '22.11.4502',
                'full_name'         => 'Siti Nurhaliza',
                'email'             => 'siti.nurhaliza@students.amikom.ac.id',
                'email_verified_at' => date('Y-m-d H:i:s'),
                'phone_number'      => '082198765432',
                'password'          => password_hash('password123', PASSWORD_BCRYPT),
                'faculty_id'        => 1,
                'study_program_id'  => 1,
                'class_id'          => 2,
                'place_of_birth'    => 'Purbalingga',
                'date_of_birth'     => '2003-08-20',
                'gender'            => 'female',
                'province'          => 'Jawa Tengah',
                'regency'           => 'Purbalingga',
                'subdistrict'       => 'Kalimanah',
                'village'           => 'Blater',
                'address'           => 'Jl. Raya Blater No. 12',
                'gpa'               => 3.75,
                'profile'           => 'default.jpg',
                'is_verified'        => 1,
                'status_account'    => 'active',
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'student_number'    => '22.12.3301',
                'full_name'         => 'Rian Ardianto',
                'email'             => 'rian.ardianto@students.amikom.ac.id',
                'email_verified_at' => date('Y-m-d H:i:s'),
                'phone_number'      => '085712344321',
                'password'          => password_hash('password123', PASSWORD_BCRYPT),
                'faculty_id'        => 1,
                'study_program_id'  => 2,
                'class_id'          => 3,
                'place_of_birth'    => 'Cilacap',
                'date_of_birth'     => '2002-11-03',
                'gender'            => 'male',
                'province'          => 'Jawa Tengah',
                'regency'           => 'Cilacap',
                'subdistrict'       => 'Kroya',
                'village'           => 'Bajing',
                'address'           => 'Jl. Jendral Sudirman No. 88',
                'gpa'               => 3.60,
                'profile'           => 'default.jpg',
                'is_verified'        => 1,
                'status_account'    => 'active',
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'student_number'    => '23.01.2210',
                'full_name'         => 'Anisa Rahmawati',
                'email'             => 'anisa.rahma@students.amikom.ac.id',
                'email_verified_at' => date('Y-m-d H:i:s'),
                'phone_number'      => '088801239876',
                'password'          => password_hash('password123', PASSWORD_BCRYPT),
                'faculty_id'        => 1,
                'study_program_id'  => 3,
                'class_id'          => 4,
                'place_of_birth'    => 'Kebumen',
                'date_of_birth'     => '2004-01-15',
                'gender'            => 'female',
                'province'          => 'Jawa Tengah',
                'regency'           => 'Kebumen',
                'subdistrict'       => 'Gombong',
                'village'           => 'Wonosigro',
                'address'           => 'Jl. Stasiun No. 05',
                'gpa'               => 3.90,
                'profile'           => 'default.jpg',
                'is_verified'        => 1,
                'status_account'    => 'active',
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'student_number'    => '22.21.1099',
                'full_name'         => 'Fajar Pratama',
                'email'             => 'fajar.pratama@students.amikom.ac.id',
                'email_verified_at' => date('Y-m-d H:i:s'),
                'phone_number'      => '081399887766',
                'password'          => password_hash('password123', PASSWORD_BCRYPT),
                'faculty_id'        => 2,
                'study_program_id'  => 4,
                'class_id'          => 5,
                'place_of_birth'    => 'Tegal',
                'date_of_birth'     => '2003-09-27',
                'gender'            => 'male',
                'province'          => 'Jawa Tengah',
                'regency'           => 'Tegal',
                'subdistrict'       => 'Slawi',
                'village'           => 'Procot',
                'address'           => 'Jl. Ahmad Yani No. 101',
                'gpa'               => 3.55,
                'profile'           => 'default.jpg',
                'is_verified'        => 1,
                'status_account'    => 'active',
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('users')->insertBatch($data);
    }
}
