<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UsersSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $data = [
            [
                'registration_main'    => 'user_reg_001',
                'student_number'       => '22.11.0001',
                'full_name'            => 'Igo Tegar Prambudhy',
                'email'                => 'igo@gmail.com',
                'email_verified_at'    => date('Y-m-d H:i:s'),
                'phone_number'         => '082111112222',
                'password'             => password_hash('password123', PASSWORD_BCRYPT),
                'faculty_params'       => 'fiki_main_001',
                'study_program_params' => 'prodi_if_01',
                'class_params'         => 'class_if22a_01',
                'place_of_birth'       => 'Banyumas',
                'date_of_birth'        => '2003-05-14',
                'gender'               => 'male',
                'province'             => 'Jawa Tengah',
                'regency'              => 'Kabupaten Banyumas',
                'subdistrict'          => 'Purwokerto Utara',
                'village'              => 'Bancarkembar',
                'address'              => 'Jl. Hr. Bunyamin No. 12',
                'gpa'                  => 3.85,
                'profile'              => 'profile-default.png',
                'otp_code'             => null,
                'otp_created_at'       => null,
                'otp_expires_at'       => null,
                'is_verified'          => 1,
                'verification_status'  => 'completed',
                'certificate_file'     => 'cert_001.pdf',
                'membership_status'    => 'candidate',
                'status_account'       => 'active',
                'remember_token'       => null,
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'registration_main'    => 'user_reg_002',
                'student_number'       => '22.11.0002',
                'full_name'            => 'Siti Nur Aini',
                'email'                => 'siti@gmail.com',
                'email_verified_at'    => $now,
                'phone_number'         => '082133334444',
                'password'             => password_hash('password123', PASSWORD_BCRYPT),
                'faculty_params'       => 'fiki_main_001',
                'study_program_params' => 'prodi_if_01',
                'class_params'         => 'class_if22b_02',
                'place_of_birth'       => 'Cilacap',
                'date_of_birth'        => '2004-01-20',
                'gender'               => 'female',
                'province'             => 'Jawa Tengah',
                'regency'              => 'Kabupaten Cilacap',
                'subdistrict'          => 'Majenang',
                'village'              => 'Jenang',
                'address'              => 'Jl. Raya Majenang No. 45',
                'gpa'                  => 3.72,
                'profile'              => 'profile-default.png',
                'otp_code'             => null,
                'otp_created_at'       => null,
                'otp_expires_at'       => null,
                'is_verified'          => 1,
                'verification_status'  => 'completed',
                'certificate_file'     => 'cert_002.pdf',
                'membership_status'    => 'candidate',
                'status_account'       => 'active',
                'remember_token'       => null,
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'registration_main'    => 'user_reg_003',
                'student_number'       => '22.12.0015',
                'full_name'            => 'Fajar Dwi Kurniawan',
                'email'                => 'fajar@gmail.com',
                'email_verified_at'    => $now,
                'phone_number'         => '082155556666',
                'password'             => password_hash('password123', PASSWORD_BCRYPT),
                'faculty_params'       => 'fiki_main_001',
                'study_program_params' => 'prodi_si_02',
                'class_params'         => 'class_si22a_03',
                'place_of_birth'       => 'Purbalingga',
                'date_of_birth'        => '2003-11-10',
                'gender'               => 'male',
                'province'             => 'Jawa Tengah',
                'regency'              => 'Kabupaten Purbalingga',
                'subdistrict'          => 'Kalimanah',
                'village'              => 'Selaganggeng',
                'address'              => 'Jl. Jend. Soedirman No. 88',
                'gpa'                  => 3.65,
                'profile'              => 'profile-default.png',
                'otp_code'             => null,
                'otp_created_at'       => null,
                'otp_expires_at'       => null,
                'is_verified'          => 1,
                'verification_status'  => 'completed',
                'certificate_file'     => 'cert_003.pdf',
                'membership_status'    => 'candidate',
                'status_account'       => 'active',
                'remember_token'       => null,
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'registration_main'    => 'user_reg_004',
                'student_number'       => '23.01.0008',
                'full_name'            => 'Nadia Putri Utami',
                'email'                => 'nadia@gmail.com',
                'email_verified_at'    => $now,
                'phone_number'         => '082177778888',
                'password'             => password_hash('password123', PASSWORD_BCRYPT),
                'faculty_params'       => 'fiki_main_001',
                'study_program_params' => 'prodi_ti_03',
                'class_params'         => 'class_bd23a_04',
                'place_of_birth'       => 'Kebumen',
                'date_of_birth'        => '2004-08-25',
                'gender'               => 'female',
                'province'             => 'Jawa Tengah',
                'regency'              => 'Kabupaten Kebumen',
                'subdistrict'          => 'Gombong',
                'village'              => 'Wonosigro',
                'address'              => 'Jl. Pahlawan No. 10',
                'gpa'                  => 3.90,
                'profile'              => 'profile-default.png',
                'otp_code'             => null,
                'otp_created_at'       => null,
                'otp_expires_at'       => null,
                'is_verified'          => 1,
                'verification_status'  => 'completed',
                'certificate_file'     => 'cert_004.pdf',
                'membership_status'    => 'member',
                'status_account'       => 'active',
                'remember_token'       => null,
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'registration_main'    => 'user_reg_005',
                'student_number'       => '22.31.0003',
                'full_name'            => 'Bagas Saputra',
                'email'                => 'bagas@gmail.com',
                'email_verified_at'    => $now,
                'phone_number'         => '082199990000',
                'password'             => password_hash('password123', PASSWORD_BCRYPT),
                'faculty_params'       => 'fbs_main_002',
                'study_program_params' => 'prodi_ilkom_04',
                'class_params'         => 'class_ik22a_05',
                'place_of_birth'       => 'Banjarnegara',
                'date_of_birth'        => '2003-03-03',
                'gender'               => 'male',
                'province'             => 'Jawa Tengah',
                'regency'              => 'Kabupaten Banjarnegara',
                'subdistrict'          => 'Bawang',
                'village'              => 'Mantrianom',
                'address'              => 'Jl. Pemuda No. 7',
                'gpa'                  => 3.50,
                'profile'              => 'profile-default.png',
                'otp_code'             => null,
                'otp_created_at'       => null,
                'otp_expires_at'       => null,
                'is_verified'          => 0,
                'verification_status'  => 'unsubmitted',
                'certificate_file'     => null,
                'membership_status'    => 'failed',
                'status_account'       => 'active',
                'remember_token'       => null,
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
        ];

        $this->db->table('users')->insertBatch($data);
    }
}
